### ISSUE TITLE
Local inference test

### ISSUE THREAD

**Issue by emepetres** [microsoft/microsoft-bonsai-api#17]
Hi, I have trained and exported a "brain" from Bonsai UI using the Moab example.

I'd like to run inference on a local machine but I'm not sure how to do it as there is no samples in this regard.

With docker I can run the exported brain which opens a server at port 5000. Then I guess I have to communicate with the brain using the bonsai api, but not sure exactly how to send an state and get a resulting action.

My two main questions are:
* How to set up config to connect the client to the local docker instance?
* To get a new event, seems that I need to specify workspace and session, but running locally I don't have the first and I don't see how to create a session without a simulator (I don't need a simulator right now, just to test inference).

Following the cartpole sample this is what I have for now:
```python
config = BonsaiClientConfig(["--api-host", "http://localhost:5000"])
client = BonsaiClient(config)

# TODO create a session

try:
    event = client.session.advance(
        workspace_name=config.workspace,
        session_id=registered_session.session_id,
        body=sim_state,
    )
    sequence_id = event.sequence_id
    print("[{}] Last Event: {}".format(time.strftime("%H:%M:%S"), event.type))
except HttpResponseError as ex:
    ....
```

Could you please indicate how to do local inference with an exported brain? A complete sample using Moab demo would be amazing :)
Thanks!

**Comment by zen-chetan** [comment]
Hi @emepetres , the exported brain provides inference via HTTP/REST calls.  You can call it directly without the Bonsai SDK.

Using your example for Moab, you can `POST` to http://localhost:5000/v1/prediction with the state encoded as a JSON dictionary in the request body, and you should get back a JSON-encoded action.

So something like... 
```bash
curl -X POST -d '{"ball_x": 0.0, "ball_y": 0.0, "ball_vel_x": 0.0, "ball_vel_y": 0.0}' http://localhost:5000/v1/prediction
```

or, in Python:
```python
import requests

state = {
  "ball_x": 0.0,
  "ball_y": 0.0,
  "ball_vel_x": 0.0,
  "ball_vel_y": 0.0
}

response = requests.post("http://localhost:500/v1/prediction", data=state)

action = response.json()
# action should be a dictionary with keys "input_pitch" and "input_roll".
```

Also available are a Swagger document at http://localhost:5000/v1/api.json and a Swagger UI at http://localhost:5000/v1/doc/index.html.

**Comment by emepetres** [comment]
Great, thanks!
