### ISSUE TITLE
Cartpole example has type issue when trying to run it as-is. 

### ISSUE THREAD

**Issue by sdk-bonsai** [microsoft/microsoft-bonsai-api#32]
The cartpole states need to be cast as floats, as inkling type mismatch occurs.

**Comment by sdk-bonsai** [comment]
@nmann4 , @shnayder @ForrestTrepte , @scotstan , @akzaidi adding the issue here, instead of bug directly. But, let me know, i can file a separate ADO ticket.

**Comment by sdk-bonsai** [comment]
This is the error in error console (either typecasting error or missing initial): 
2/22 6:40 PM:
The state value received from simulator id 1314504238_10.244.78.89 is missing a value for cart_position, cart_velocity, pole_angle, pole_angular_velocity. This episode will be terminated. This may be due to a bug in your simulator or Inkling code. Previous state: {} Previous action: {}

Brain link: https://preview.bons.ai/workspaces/69394e91-046a-41fe-8e9b-dca4664e8d94/brains/cptest3/versions/1/train . This is reproducible easily with an unmanaged sim. Just pull the repo. Run an unmanaged local sim and try to connect using demo cartpole inkling.

**Comment by akzaidi** [comment]
Hey @sdk-bonsai  - can you double-check you have the latest [inkling](https://github.com/microsoft/microsoft-bonsai-api/blob/main/Python/samples/cartpole/machine_teacher.ink), [`sim/cartpole.py`](https://github.com/microsoft/microsoft-bonsai-api/blob/main/Python/samples/cartpole/sim/cartpole.py) and [`main.py`](https://github.com/microsoft/microsoft-bonsai-api/blob/main/Python/samples/cartpole/main.py)? 

`main.py` and `sim/cartpole.py` were updated last week to match the in-platform sample. It looks like your inkling is up-to-date but your `sim/cartpole.py` is not. Note the [updated state definition](https://github.com/microsoft/microsoft-bonsai-api/blob/main/Python/samples/cartpole/sim/cartpole.py#L122-L134).

**Comment by sdk-bonsai** [comment]
Yep, I pulled it a day before Victor committed the modified state definitions and inkling. Replacing with version inkling worked. The new version has more states with velocities at different places on the pole and different naming also.
