### ISSUE TITLE
Failed to build C# SDK

### ISSUE THREAD

**Issue by JohnMasen** [microsoft/microsoft-bonsai-api#9]
Build project "Microsoft.Bonsai.Api.Simulator.csproj" failed with following error, seems some partial class file is missing in the source.

`1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(42,13,42,18): error CS0103: The name 'Clent' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(205,13,205,29): error CS0103: The name 'cacellationToken' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(213,13,213,38): error CS0103: The name 'HttpStatusCode_statusCode' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(217,22,217,33): error CS0103: The name '_statusCode' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(219,119,219,130): error CS0103: The name '_statusCode' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(238,17,238,26): error CS0103: The name 'exRequest' does not exist in the current context
1>D:\GithubRoot\microsoft-bonsai-api\CSharp\Microsoft.Bonsai.Api\Simulator\Generated\Session.cs(265,22,265,33): error CS0103: The name '_statusCode' does not exist in the current context`

### BuildTool: VS2019 16.7.1

**Comment by mayankiitg** [comment]
Hi John,
Thanks for posting the concern and apologies for late response..
We merged a wrong commit, that led to build failures in C# SDK. Going to push a fix by today.

**Comment by mayankiitg** [comment]
it's fixed now.
